### ISSUE TITLE
Retry test results are showing failed in VS2017 test runner

### ISSUE THREAD

**Issue by jeevaprakashdr** [pvlakshm/MSTestEx#130] opened 2019-03-26 07:20 UTC
## Description
> A test methos set to retry in set number of times shown as failed in VS2017 test runner.

## Steps to reproduce
> setup a test in VS2017. Set method to retry 5 times.

## Expected behavior
> If test failed first attempt it should retry to execute the test and on second attempt if test run successfully test runner should show array of test results and test ruunner highlight test as successfull.

## Actual behavior
> Test runner show test as failed.

## Environment
> v1.0.2

## How i have overcome as of now.
> on success of a retry, atpreset im filtering failed testresult and returning only success trest result from arrat of testresult.

**Comment by pvlakshm** [comment] 2019-04-02 09:30
@jeevaprakashdr, can you see if the [RetryAttribute documentation](https://github.com/pvlakshm/MSTestEx/blob/master/docs/AttributeEx/RetryAttribute.md) matches with your expectation, please.

**Comment by jeevaprakashdr** [comment] 2019-04-06 18:12
@pvlakshm  Yes, I understand. The only failed test is attempted to execute once again. As stated in the documentation 

>  Each execution attempt is recorded as a child test.

the result of the retry test is a child test results, but the test runner considers it as a failed test. As the top of the TestResult[] stores failed attempt result.

**Comment by pvlakshm** [comment] 2019-05-16 11:27
This is by design.  
In this case, there will be 2 child results - the first will have an outcome of "failed", and the second will have an outcome of "passed". However, since at least one of the attempts had a failed, the overall test is considered as "failed".  
Would you prefer that the overall test be marked "passed"? If so, why?

**Comment by pvlakshm** [comment] 2019-05-19 13:27
If a test passes on rerun, it could be a potentially flaky test, and must be investigated. If the overall result were to be marked "passed", then one might never come to know about this and never investigate deeper. Hence the overall result is marked "failed".
This is by design, and hence I will close this issue.

**Closed as completed by pvlakshm** 2019-05-19 13:27 UTC

**Comment by rajababuk** [comment] 2019-06-30 05:00
Can someone please help how to read Test Results which has child results - failed, failed and passed, so we can mark the test case as finally Passed.

I understand, if a test If a test passes on rerun, it could be a potentially flaky test, and must be investigated. In my current situation where I don't see any value add if the overall result is marked "failed" once it is passed after re-run.
